export const MLB_TEAMS = [
  { id: 'ARI', name: 'Arizona Diamondbacks' },
  { id: 'ATL', name: 'Atlanta Braves' },
  { id: 'BAL', name: 'Baltimore Orioles' },
  { id: 'BOS', name: 'Boston Red Sox' },
  { id: 'CHC', name: 'Chicago Cubs' },
  { id: 'CWS', name: 'Chicago White Sox' },
  { id: 'CIN', name: 'Cincinnati Reds' },
  { id: 'CLE', name: 'Cleveland Guardians' },
  { id: 'COL', name: 'Colorado Rockies' },
  { id: 'DET', name: 'Detroit Tigers' },
  { id: 'HOU', name: 'Houston Astros' },
  { id: 'KC', name: 'Kansas City Royals' },
  { id: 'LAA', name: 'Los Angeles Angels' },
  { id: 'LAD', name: 'Los Angeles Dodgers' },
  { id: 'MIA', name: 'Miami Marlins' },
  { id: 'MIL', name: 'Milwaukee Brewers' },
  { id: 'MIN', name: 'Minnesota Twins' },
  { id: 'NYM', name: 'New York Mets' },
  { id: 'NYY', name: 'New York Yankees' },
  { id: 'ATH', name: 'The Athletics' },
  { id: 'PHI', name: 'Philadelphia Phillies' },
  { id: 'PIT', name: 'Pittsburgh Pirates' },
  { id: 'SD', name: 'San Diego Padres' },
  { id: 'SF', name: 'San Francisco Giants' },
  { id: 'SEA', name: 'Seattle Mariners' },
  { id: 'STL', name: 'St. Louis Cardinals' },
  { id: 'TB', name: 'Tampa Bay Rays' },
  { id: 'TEX', name: 'Texas Rangers' },
  { id: 'TOR', name: 'Toronto Blue Jays' },
  { id: 'WSH', name: 'Washington Nationals' }
];

